# Generated by Django 5.0.3 on 2024-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
    ]
